// Generated by scripts/pet_frames.py from assets/pet/*.png. Do not edit by hand.
import type { ImageSourcePropType } from 'react-native';

export type MarkKind = 'float' | 'wobble' | 'burst' | 'zzz';

export interface PoseArt {
  /** width / height of every image in this pose */
  aspect: number;
  /** how much bigger each tail frame is than the picture, per side, as [x, y] fractions of the picture */
  pad: [number, number];
  /** the body with the tail bent a little further in each frame (middle frame is the neutral one) */
  frames: ImageSourcePropType[];
  /** patch that draws the mouth open, as [left, top, width, height] fractions of the picture */
  mouth: { src: ImageSourcePropType; box: [number, number, number, number] };
  marks: { src: ImageSourcePropType; box: [number, number, number, number]; kind: MarkKind; delay: number; dir: [number, number] }[];
}

export const POSE_ART = {
  happy: {
    aspect: 1.0953,
    pad: [0.0593, 0.0649],
    frames: [
      require('@/assets/pet/anim/happy/tail-0.webp'),
      require('@/assets/pet/anim/happy/tail-1.webp'),
      require('@/assets/pet/anim/happy/tail-2.webp'),
      require('@/assets/pet/anim/happy/tail-3.webp'),
      require('@/assets/pet/anim/happy/tail-4.webp'),
      require('@/assets/pet/anim/happy/tail-5.webp'),
      require('@/assets/pet/anim/happy/tail-6.webp'),
      require('@/assets/pet/anim/happy/tail-7.webp'),
      require('@/assets/pet/anim/happy/tail-8.webp'),
      require('@/assets/pet/anim/happy/tail-9.webp'),
      require('@/assets/pet/anim/happy/tail-10.webp'),
      require('@/assets/pet/anim/happy/tail-11.webp'),
      require('@/assets/pet/anim/happy/tail-12.webp'),
    ],
    mouth: { src: require('@/assets/pet/anim/happy/mouth.webp'), box: [0.4296, 0.3712, 0.1481, 0.1055] },
    marks: [
      { src: require('@/assets/pet/anim/happy/mark-0.webp'), box: [0.0444, 0.0487, 0.1296, 0.1278], kind: 'float', delay: 0, dir: [-0.74, -0.67] },
      { src: require('@/assets/pet/anim/happy/mark-1.webp'), box: [0.8241, 0.574, 0.1019, 0.1014], kind: 'float', delay: 700, dir: [0.96, 0.29] },
    ],
  },
  curious: {
    aspect: 1.1694,
    pad: [0.0601, 0.0702],
    frames: [
      require('@/assets/pet/anim/curious/tail-0.webp'),
      require('@/assets/pet/anim/curious/tail-1.webp'),
      require('@/assets/pet/anim/curious/tail-2.webp'),
      require('@/assets/pet/anim/curious/tail-3.webp'),
      require('@/assets/pet/anim/curious/tail-4.webp'),
      require('@/assets/pet/anim/curious/tail-5.webp'),
      require('@/assets/pet/anim/curious/tail-6.webp'),
      require('@/assets/pet/anim/curious/tail-7.webp'),
      require('@/assets/pet/anim/curious/tail-8.webp'),
      require('@/assets/pet/anim/curious/tail-9.webp'),
      require('@/assets/pet/anim/curious/tail-10.webp'),
      require('@/assets/pet/anim/curious/tail-11.webp'),
      require('@/assets/pet/anim/curious/tail-12.webp'),
    ],
    mouth: { src: require('@/assets/pet/anim/curious/mouth.webp'), box: [0.4753, 0.376, 0.0777, 0.0909] },
    marks: [
      { src: require('@/assets/pet/anim/curious/mark-0.webp'), box: [0.8339, 0.0661, 0.1237, 0.2293], kind: 'wobble', delay: 0, dir: [0.82, -0.57] },
    ],
  },
  cheering: {
    aspect: 1.2029,
    pad: [0.0596, 0.0717],
    frames: [
      require('@/assets/pet/anim/cheering/tail-0.webp'),
      require('@/assets/pet/anim/cheering/tail-1.webp'),
      require('@/assets/pet/anim/cheering/tail-2.webp'),
      require('@/assets/pet/anim/cheering/tail-3.webp'),
      require('@/assets/pet/anim/cheering/tail-4.webp'),
      require('@/assets/pet/anim/cheering/tail-5.webp'),
      require('@/assets/pet/anim/cheering/tail-6.webp'),
      require('@/assets/pet/anim/cheering/tail-7.webp'),
      require('@/assets/pet/anim/cheering/tail-8.webp'),
      require('@/assets/pet/anim/cheering/tail-9.webp'),
      require('@/assets/pet/anim/cheering/tail-10.webp'),
      require('@/assets/pet/anim/cheering/tail-11.webp'),
      require('@/assets/pet/anim/cheering/tail-12.webp'),
    ],
    mouth: { src: require('@/assets/pet/anim/cheering/mouth.webp'), box: [0.379, 0.2807, 0.1908, 0.2541] },
    marks: [
      { src: require('@/assets/pet/anim/cheering/mark-0.webp'), box: [0.0204, 0.1988, 0.1065, 0.1322], kind: 'burst', delay: 0, dir: [-0.91, -0.42] },
      { src: require('@/assets/pet/anim/cheering/mark-1.webp'), box: [0.885, 0.2264, 0.0945, 0.1322], kind: 'burst', delay: 250, dir: [0.93, -0.37] },
      { src: require('@/assets/pet/anim/cheering/mark-2.webp'), box: [0.0153, 0.3371, 0.1065, 0.0943], kind: 'burst', delay: 500, dir: [-0.98, -0.22] },
      { src: require('@/assets/pet/anim/cheering/mark-3.webp'), box: [0.8825, 0.3648, 0.1031, 0.0953], kind: 'burst', delay: 750, dir: [0.99, -0.17] },
    ],
  },
  sleepy: {
    aspect: 1.3333,
    pad: [0.0601, 0.0801],
    frames: [
      require('@/assets/pet/anim/sleepy/tail-0.webp'),
      require('@/assets/pet/anim/sleepy/tail-1.webp'),
      require('@/assets/pet/anim/sleepy/tail-2.webp'),
      require('@/assets/pet/anim/sleepy/tail-3.webp'),
      require('@/assets/pet/anim/sleepy/tail-4.webp'),
      require('@/assets/pet/anim/sleepy/tail-5.webp'),
      require('@/assets/pet/anim/sleepy/tail-6.webp'),
      require('@/assets/pet/anim/sleepy/tail-7.webp'),
      require('@/assets/pet/anim/sleepy/tail-8.webp'),
      require('@/assets/pet/anim/sleepy/tail-9.webp'),
      require('@/assets/pet/anim/sleepy/tail-10.webp'),
      require('@/assets/pet/anim/sleepy/tail-11.webp'),
      require('@/assets/pet/anim/sleepy/tail-12.webp'),
    ],
    mouth: { src: require('@/assets/pet/anim/sleepy/mouth.webp'), box: [0.3232, 0.674, 0.1022, 0.081] },
    marks: [
      { src: require('@/assets/pet/anim/sleepy/mark-0.webp'), box: [0.6519, 0.3103, 0.0622, 0.0948], kind: 'zzz', delay: 0, dir: [0.86, -0.5] },
      { src: require('@/assets/pet/anim/sleepy/mark-1.webp'), box: [0.73, 0.2053, 0.0753, 0.1114], kind: 'zzz', delay: 450, dir: [0.83, -0.56] },
      { src: require('@/assets/pet/anim/sleepy/mark-2.webp'), box: [0.8163, 0.0875, 0.0822, 0.1243], kind: 'zzz', delay: 900, dir: [0.81, -0.59] },
    ],
  },
} satisfies Record<string, PoseArt>;
